name: ext_video_player
description: Flutter plugin for displaying inline  with other Flutter
  widgets on Android and iOS. This plugin also supports playing youtube videos & RTMP Streams
version: 0.1.2
homepage: https://github.com/ponnamkarthik/ext_video_player

flutter:
  plugin:
    platforms:
      android:
        package: ext.videoplayer
        pluginClass: ExtVideoPlayerPlugin
      ios:
        pluginClass: FLTExtVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  video_player_platform_interface: ^6.2.1

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web: ^2.1.2
  meta: ^1.9.1
  
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  pigeon: ^14.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
